// Code generated by MockGen. DO NOT EDIT.
// Source: provider.go

// Package mock_main is a generated GoMock package.
package mock_provider

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockProvider is a mock of Provider interface
type MockProvider struct {
	ctrl     *gomock.Controller
	recorder *MockProviderMockRecorder
}

// MockProviderMockRecorder is the mock recorder for MockProvider
type MockProviderMockRecorder struct {
	mock *MockProvider
}

// NewMockProvider creates a new mock instance
func NewMockProvider(ctrl *gomock.Controller) *MockProvider {
	mock := &MockProvider{ctrl: ctrl}
	mock.recorder = &MockProviderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockProvider) EXPECT() *MockProviderMockRecorder {
	return m.recorder
}

// Encrypt mocks base method
func (m *MockProvider) Encrypt() (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Encrypt")
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Encrypt indicates an expected call of Encrypt
func (mr *MockProviderMockRecorder) Encrypt() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Encrypt", reflect.TypeOf((*MockProvider)(nil).Encrypt))
}

// Decrypt mocks base method
func (m *MockProvider) Decrypt() (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Decrypt")
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Decrypt indicates an expected call of Decrypt
func (mr *MockProviderMockRecorder) Decrypt() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Decrypt", reflect.TypeOf((*MockProvider)(nil).Decrypt))
}

// DecryptEnv mocks base method
func (m *MockProvider) DecryptEnv() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "DecryptEnv")
}

// DecryptEnv indicates an expected call of DecryptEnv
func (mr *MockProviderMockRecorder) DecryptEnv() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DecryptEnv", reflect.TypeOf((*MockProvider)(nil).DecryptEnv))
}
